# Generated by Django 2.0.1 on 2019-02-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='timetable',
            new_name='timetable_url',
        ),
    ]
